export const coursesData = [
  {
    id: 1,
    title: " Web Development Bootcamp",
    instructor: "Sarah Johnson",
    category: "Development",
    duration: "6h 30m",
    students: "1.2k",
    price: "$49",
    isFree: false,
    imageUrl: "/hero.png",
    description:
      "Master web development from scratch. Learn HTML, CSS, JavaScript, React, and build real-world projects that will help you land your dream job.",
    level: "Beginner",
    language: "English",
    curriculum: [
      {
        id: "module-1",
        title: "Introduction to Web Development",
        lessons: [
          { id: 1, title: "What is Web Development?", duration: "5:30" },
          { id: 2, title: "Setting Up Your Development Environment", duration: "12:45" },
          { id: 3, title: "HTML Basics", duration: "18:20" },
          { id: 4, title: "CSS Fundamentals", duration: "22:10" },
        ],
      },
      {
        id: "module-2",
        title: "JavaScript Essentials",
        lessons: [
          { id: 5, title: "JavaScript Syntax and Variables", duration: "15:40" },
          { id: 6, title: "Functions and Scope", duration: "20:15" },
          { id: 7, title: "Working with Arrays and Objects", duration: "25:30" },
          { id: 8, title: "DOM Manipulation", duration: "18:50" },
        ],
      },
      {
        id: "module-3",
        title: "React Fundamentals",
        lessons: [
          { id: 9, title: "Introduction to React", duration: "10:20" },
          { id: 10, title: "Components and Props", duration: "22:40" },
          { id: 11, title: "State and Lifecycle", duration: "19:15" },
          { id: 12, title: "Hooks in React", duration: "28:30" },
        ],
      },
      {
        id: "module-4",
        title: "Building Real Projects",
        lessons: [
          { id: 13, title: "Project Planning and Setup", duration: "14:25" },
          { id: 14, title: "Building a Todo App", duration: "35:10" },
          { id: 15, title: "Creating a Weather Dashboard", duration: "42:20" },
          { id: 16, title: "Final Project Walkthrough", duration: "38:45" },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "UI/UX Design Fundamentals",
    instructor: "Michael Chen",
    category: "Design",
    duration: "4h 15m",
    students: "850",
    price: "$39",
    isFree: false,
    imageUrl: "/hero.png",
    description:
      "Learn the principles of user interface and user experience design. Master design tools and create beautiful, user-friendly interfaces.",
    level: "Beginner",
    language: "English",
  },
  {
    id: 3,
    title: "Introduction to Data Science",
    instructor: "Dr. Emily Roberts",
    category: "Data Science",
    duration: "8h 45m",
    students: "2.1k",
    isFree: true,
    imageUrl: "/hero.png",
    description:
      "Discover the fundamentals of data science, including data analysis, visualization, and machine learning basics.",
    level: "Beginner",
    language: "English",
  },
  {
    id: 4,
    title: "Mobile App Development",
    instructor: "David Martinez",
    category: "Development",
    duration: "5h 20m",
    students: "950",
    price: "$44",
    isFree: false,
    imageUrl: "/hero.png",
    description:
      "Build native mobile applications for iOS and Android using React Native. Learn to create cross-platform apps efficiently.",
    level: "Intermediate",
    language: "English",
  },
  {
    id: 5,
    title: "Digital Marketing Mastery",
    instructor: "Jennifer Lee",
    category: "Marketing",
    duration: "3h 50m",
    students: "1.5k",
    price: "$35",
    isFree: false,
    imageUrl: "/hero.png",
    description:
      "Master digital marketing strategies including SEO, social media marketing, content marketing, and analytics.",
    level: "Beginner",
    language: "English",
  },
  {
    id: 6,
    title: "Machine Learning Essentials",
    instructor: "Prof. James Wilson",
    category: "Data Science",
    duration: "7h 10m",
    students: "1.8k",
    price: "$55",
    isFree: false,
    imageUrl: "/hero.png",
    description:
      "Understand the core concepts of machine learning and build predictive models using popular algorithms and frameworks.",
    level: "Advanced",
    language: "English",
  },
  {
    id: 7,
    title: "Advanced JavaScript",
    instructor: "Alex Turner",
    category: "Development",
    duration: "5h 45m",
    students: "1.4k",
    price: "$42",
    isFree: false,
    imageUrl: "/hero.png",
    description:
      "Deep dive into advanced JavaScript concepts including closures, async programming, design patterns, and performance optimization.",
    level: "Advanced",
    language: "English",
  },
  {
    id: 8,
    title: "Graphic Design Masterclass",
    instructor: "Sophie Anderson",
    category: "Design",
    duration: "4h 30m",
    students: "920",
    price: "$38",
    isFree: false,
    imageUrl: "/hero.png",
    description:
      "Learn professional graphic design techniques and master industry-standard tools to create stunning visual content.",
    level: "Intermediate",
    language: "English",
  },
  {
    id: 9,
    title: "Business Strategy & Planning",
    instructor: "Robert Chen",
    category: "Business",
    duration: "6h 15m",
    students: "1.1k",
    isFree: true,
    imageUrl: "/hero.png",
    description:
      "Develop strategic thinking skills and learn to create effective business plans for startups and established companies.",
    level: "Intermediate",
    language: "English",
  },
]
